cmake_minimum_required(VERSION 3.13)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(PICO_BOARD pico2 CACHE STRING "Board type")
include(pico_sdk_import.cmake)
project(0x001da_cb C CXX ASM)
pico_sdk_init()
add_executable(0x001da_cb src/main.c)
target_link_libraries(0x001da_cb pico_stdlib)

